### ISSUE TITLE
Similar projects

### ISSUE THREAD

**Issue by szepeviktor** [ItalyStrap/html#1]
- https://github.com/decodelabs/tagged
- https://github.com/szepeviktor/Toolkit4WP/blob/master/src/helpers.php#L17 (my oversimplified ones)
- https://github.com/drupol/htmltag

**Comment by overclokk** [comment]
Yes, I know there are plenty of them, but what I need with this is to have an API to give to the user the ability to filter tags in pages in case they need to change style on runtime, with this API I can remove Bootstrap css in toto without issues because now is too coupled with ItalyStrap.

As you can see here https://github.com/ItalyStrap/italystrap/blob/Dev/templates/index.php with this approach I can simply use some configuration file like this https://github.com/ItalyStrap/italystrap/blob/Dev/config/html_attrs.php to change style, it is not finished yet but it works as expected.
